### ISSUE TITLE
2018.11.12-2018.11.18周总结

### ISSUE THREAD

**Issue by tang119** [tang119/Curriculum-summary#14]
本周学了
- css3 flex-box弹性盒子（https://github.com/tang119/blog/issues/33）
flex-box存在兼容性问题，只兼容现代浏览器（ie11及以上）。
不同浏览器的兼容需要添加浏览器前缀，可以通过webpack自动添加前缀。
一个很实用的是解决不设置宽高的情况下实现盒子的水平垂直居中
```css
.box{
    display:flex;
    justify-content:center;//水平居中
    align-items:center;//垂直居中
}
```

- webpack入门（https://www.jianshu.com/p/c3112b88349c）
这是一个可以打包css/img/js的webpack项目。es6可以自动编译。内置简单的服务器。可以做到热加载，npm run dev开始运行。npm start开始编译。img、css文件都会打包到单独的文件夹里。dist目录不需要手动清除。
代码地址（https://github.com/tang119/webpack/tree/master/project_demo/speedm）
